# Generated by Django 4.2 on 2025-03-14 13:18

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_userprofile_contact_remove_userprofile_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionrequest',
            name='error_photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='error_photos/'),
        ),
    ]
