# Generated by Django 4.2 on 2025-03-15 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='solution_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user.solutionrequest'),
        ),
    ]
