# Generated by Django 4.2 on 2025-03-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.CharField(default='default_recipient_username', max_length=100, null=True),
        ),
    ]
