# Generated by Django 4.2 on 2025-03-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_message_conversation_alter_message_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionrequest',
            name='error_photo',
            field=models.ImageField(default='default.jpg', upload_to='error_photos/'),
        ),
    ]
