# Generated by Django 4.2 on 2025-03-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_solutionrequest_error_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionrequest',
            name='error_photo',
            field=models.ImageField(upload_to='error_photos/'),
        ),
    ]
