# Generated by Django 4.2 on 2025-04-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
