# Generated by Django 4.2 on 2025-04-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
    ]
