# Generated by Django 4.2 on 2025-04-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_feedback_created_at_alter_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
    ]
