# Generated by Django 4.2 on 2025-04-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_feedback_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
    ]
